"""
routers/chat.py
---------------
POST /api/chat

Accepts a natural-language question about a previously processed repository
and returns an answer with source information.

Integration boundary
--------------------
The RAG pipeline (vector search + LLM generation) is implemented by Person C.
This router validates the incoming request and delegates to a clearly defined
integration point.

When Person C's rag.py is ready, connect it in ``_query_rag()`` below.

This file does NOT:
- Implement vector search
- Implement embeddings
- Call an LLM
- Import indexer.py or rag.py
- Return fake/hardcoded AI answers
"""

import logging

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

logger = logging.getLogger(__name__)

router = APIRouter()


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    question: str


def _validate_question(question: str) -> str:
    """
    Validate and strip the question string.
    Raises an HTTPException 400 if the question is empty or only whitespace.
    """
    if not question or not question.strip():
        raise HTTPException(
            status_code=400,
            detail={"success": False, "error": "Question cannot be empty"},
        )
    return question.strip()


class SourceInfo(BaseModel):
    """Metadata about a repository source returned with an answer."""
    file: str | None = None
    lines: str | None = None
    commit: str | None = None
    author: str | None = None
    date: str | None = None
    type: str  # "code" | "commit" | "documentation"


class ChatResponse(BaseModel):
    success: bool
    answer: str
    sources: list[SourceInfo]


class ErrorResponse(BaseModel):
    success: bool = False
    error: str


# ---------------------------------------------------------------------------
# Integration boundary for Person C
# ---------------------------------------------------------------------------

def _query_rag(question: str) -> tuple[str, list[dict]]:
    """
    Integration point — connect Person C's RAG pipeline here.

    When Person C's ``rag.py`` (or equivalent) is ready, replace the body of
    this function with the real call, for example:

        from services.rag import query_repository
        answer, sources = query_repository(question)
        return answer, sources

    The function must return:
        answer  : str          — the LLM-generated answer
        sources : list[dict]   — list of source metadata dicts, e.g.
                                 [{"file": "src/auth.py", "lines": "10-45",
                                   "type": "code"}, ...]

    Until Person C's implementation is connected, this function raises a
    ``NotImplementedError`` so the endpoint returns a clear HTTP 503 response
    instead of a silent or misleading answer.

    DO NOT implement RAG logic here.
    """
    # TODO (Person C): Replace the raise below with the real RAG call:
    #   from services.rag import query_repository
    #   return query_repository(question)
    raise NotImplementedError(
        "RAG pipeline not yet connected. "
        "Person C must implement services/rag.py and connect it in "
        "routers/chat.py :: _query_rag()."
    )


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


@router.post(
    "/api/chat",
    response_model=ChatResponse,
    responses={
        400: {"model": ErrorResponse},
        500: {"model": ErrorResponse},
        503: {"model": ErrorResponse},
    },
    summary="Ask a Question About the Repository",
    description=(
        "Send a natural-language question about the processed repository. "
        "Answers are generated by Person C's RAG pipeline (not yet connected)."
    ),
)
async def chat(request: ChatRequest):
    """
    Chat endpoint.

    Validates the question and delegates to the RAG integration boundary.
    Returns the answer and source information.
    """
    question = _validate_question(request.question)
    logger.info("Chat request received: %r", question)

    try:
        answer, raw_sources = _query_rag(question)

        # Normalise sources into SourceInfo objects
        sources: list[SourceInfo] = []
        for src in raw_sources:
            try:
                sources.append(SourceInfo(**src))
            except Exception:
                logger.warning("Could not parse source metadata: %s", src)

        logger.info("Chat response generated for question: %r", question)
        return ChatResponse(success=True, answer=answer, sources=sources)

    except NotImplementedError as exc:
        # Person C's RAG pipeline is not yet connected
        logger.warning("RAG pipeline not connected: %s", exc)
        raise HTTPException(
            status_code=503,
            detail={
                "success": False,
                "error": (
                    "The AI answer pipeline is not yet available. "
                    "Please wait for the RAG integration to be completed."
                ),
            },
        )

    except ValueError as exc:
        # Could be raised by Person C's implementation (e.g. no repo indexed)
        error_msg = str(exc)
        logger.warning("Chat validation error: %s", error_msg)
        raise HTTPException(
            status_code=400,
            detail={"success": False, "error": error_msg},
        )

    except Exception as exc:
        logger.exception("Unexpected error in /api/chat for question: %r", question)
        raise HTTPException(
            status_code=500,
            detail={"success": False, "error": "Failed to generate an answer"},
        )
